SELECT I.EMPLOYEE_NAME, I.ORGANIZATION_CODE--, KT.TEST_GRADE
FROM KOREAN_TEST KT , HR_MASTER_INFO I
WHERE KT.EMPLOYEE_KEY = I.EMPLOYEE_KEY
ORDER BY KT.TEST_GRADE DESC ;

SELECT I.ORGANIZATION_CODE, SUM(ET.TEST_GRADE) AS S
FROM ENGLISH_TEST ET, HR_MASTER_INFO I
WHERE ET.EMPLOYEE_KEY = I.EMPLOYEE_KEY
GROUP BY I.ORGANIZATION_CODE
ORDER BY S DESC;

SELECT ET.TEST_GRADE
FROM ENGLISH_TEST ET, HR_MASTER_INFO I
WHERE I.EMPLOYEE_KEY = ET.EMPLOYEE_KEY ;

-- ENGLISH 데이터 입력
UPDATE HR_MASTER_INFO I
SET I.ENGLISH_GRADE =
(SELECT ET.TEST_GRADE
 FROM ENGLISH_TEST ET
 WHERE I.EMPLOYEE_KEY = ET.EMPLOYEE_KEY) ;
 
 
-- MATH 데이터 입력
UPDATE HR_MASTER_INFO I
SET I.MATH_GRADE =
(SELECT MT.TEST_GRADE
 FROM MATH_TEST MT
 WHERE I.EMPLOYEE_KEY = MT.EMPLOYEE_KEY) ;


-- KOREAN 데이터 입력
UPDATE HR_MASTER_INFO I
SET I.KOREAN_GRADE =
(SELECT KT.TEST_GRADE
 FROM KOREAN_TEST KT
 WHERE I.EMPLOYEE_KEY = KT.EMPLOYEE_KEY) ;




--#3

SELECT 
FROM HR_MASTER_INFO I LEFT JOIN HR_CODE_COMMON C
ON I.ORGANIZATION_CODE = C.CODE_CD
ORDER BY I.EMPLOYEE_KEY ;

select I.EMPLOYEE_NAME, I.ORGANIZATION_CODE, I.ORGANIZATION_NAME, I.JOB_TITlE_NAME
from HR_MASTER_INFO i inner join HR_CODE_COMMON c
on I.ORGANIZATION_CODE=C.CODE_CD
where I.ORGANIZATION_CODE between '1100' and '1400'
group by I.EMPLOYEE_NAME, I.ORGANIZATION_CODE, I.ORGANIZATION_NAME, I.JOB_TITlE_NAME;


UPDATE HR_MASTER_INFO I
SET I.ORGANIZATION_NAME =
(SELECT C.CODE_NAME
 FROM HR_CODE_COMMON C
 WHERE I.ORGANIZATION_CODE=C.CODE_CD ) ;