CREATE TABLE HAEUN.AC_CODE_GRP
(
  GRP_CD               VARCHAR2(4 BYTE)         NOT NULL,
  GRP_NM               VARCHAR2(200 BYTE),
  AC_LEVEL             VARCHAR2(1 BYTE),
  DC_CLS               VARCHAR2(1 BYTE),
  PARENT_CD1           VARCHAR2(4 BYTE),
  PARENT_CD2           VARCHAR2(4 BYTE),
  PARENT_CD3           VARCHAR2(4 BYTE),
  PARENT_CD4           VARCHAR2(4 BYTE)
)
TABLESPACE HAEUN_DAT;


CREATE UNIQUE INDEX HAEUN.AC_CODE_GRP_PK ON HAEUN.AC_CODE_GRP
(GRP_CD)
LOGGING
TABLESPACE HAEUN_IDX;

ALTER TABLE HAEUN.AC_CODE_GRP ADD (
  CONSTRAINT AC_CODE_GRP_PK
  PRIMARY KEY
  (GRP_CD)
  USING INDEX HAEUN.AC_CODE_GRP_PK
  ENABLE VALIDATE);


CREATE TABLE HAEUN.AC_code_dtl
(
    DTL_CD          VARCHAR2 (8 Byte)       NOT NULL,
    GRP_CD          VARCHAR2 (4 Byte),
    DTL_SEQ         VARCHAR2 (4 Byte),
    DTL_NM          VARCHAR2 (200 Byte),
    DESCR           VARCHAR2 (200 Byte)
)
TABLESPACE HAEUN_DAT;


CREATE UNIQUE INDEX HAEUN.AC_code_dtl_PK ON HAEUN.AC_code_dtl
(DTL_CD)
LOGGING
TABLESPACE HAEUN_IDX;

ALTER TABLE HAEUN.AC_CODE_GRP ADD (
    PRIMARY KEY
    (DTL_CD)
    USING INDEX HAEUN.AC_code_dtl_PK
    ENABLE VALIDATE);