DROP TABLE HAEUN.HR_MASTER_INFO PURGE;

CREATE TABLE HAEUN.HR_MASTER_INFO
(
  EMPLOYEE_KEY                  VARCHAR2(10 BYTE)      NOT NULL,
  EMPLOYEE_NAME                 VARCHAR2(30 BYTE)      NOT NULL,
  ORGANIZATION_CODE             VARCHAR2(7 BYTE)       NOT NULL
)
TABLESPACE HAEUN_DAT;


CREATE UNIQUE INDEX HAEUN.HR_MASTER_INFO_PK ON HAEUN.HR_MASTER_INFO
(EMPLOYEE_KEY)
LOGGING
TABLESPACE HAEUN_IDX;

ALTER TABLE HAEUN.HR_MASTER_INFO ADD (
  CONSTRAINT HR_MASTER_INFO_PK
  PRIMARY KEY
  (EMPLOYEE_KEY)
  USING INDEX HAEUN.HR_MASTER_INFO_PK
  ENABLE VALIDATE);


Insert into HAEUN.HR_MASTER_INFO   (EMPLOYEE_KEY, EMPLOYEE_NAME, ORGANIZATION_CODE) Values   ('140305', '¼³¹Î¼®', '2500100');
Insert into HAEUN.HR_MASTER_INFO   (EMPLOYEE_KEY, EMPLOYEE_NAME, ORGANIZATION_CODE) Values   ('140922', '¾È³²±Ô', '2500100');
Insert into HAEUN.HR_MASTER_INFO   (EMPLOYEE_KEY, EMPLOYEE_NAME, ORGANIZATION_CODE) Values   ('210713', '¾çÇý¸°', '2500100');
Insert into HAEUN.HR_MASTER_INFO   (EMPLOYEE_KEY, EMPLOYEE_NAME, ORGANIZATION_CODE) Values   ('060211', 'ÃÖÇÏÀº', '2500100');
Insert into HAEUN.HR_MASTER_INFO   (EMPLOYEE_KEY, EMPLOYEE_NAME, ORGANIZATION_CODE) Values   ('070102', '±è¹®ÁÖ', '2300400');
Insert into HAEUN.HR_MASTER_INFO   (EMPLOYEE_KEY, EMPLOYEE_NAME, ORGANIZATION_CODE) Values   ('071001', 'Á¤¿îÇÏ', '2300400');
Insert into HAEUN.HR_MASTER_INFO   (EMPLOYEE_KEY, EMPLOYEE_NAME, ORGANIZATION_CODE) Values   ('120104', '±èÀÎ¼ö', '2300400');
Insert into HAEUN.HR_MASTER_INFO   (EMPLOYEE_KEY, EMPLOYEE_NAME, ORGANIZATION_CODE) Values   ('130520', 'ÀÓÁ¤ºó', '2300400');
Insert into HAEUN.HR_MASTER_INFO   (EMPLOYEE_KEY, EMPLOYEE_NAME, ORGANIZATION_CODE) Values   ('160502', '¿ø´ë°Ç', '2300400');
Insert into HAEUN.HR_MASTER_INFO   (EMPLOYEE_KEY, EMPLOYEE_NAME, ORGANIZATION_CODE) Values   ('170302', '°í°ÇÈñ', '2300400');
Insert into HAEUN.HR_MASTER_INFO   (EMPLOYEE_KEY, EMPLOYEE_NAME, ORGANIZATION_CODE) Values   ('210809', '¾öÁö', '3200400');
Insert into HAEUN.HR_MASTER_INFO   (EMPLOYEE_KEY, EMPLOYEE_NAME, ORGANIZATION_CODE) Values   ('090608', 'ÀÌ³²½Å', '1400500');
Insert into HAEUN.HR_MASTER_INFO   (EMPLOYEE_KEY, EMPLOYEE_NAME, ORGANIZATION_CODE) Values   ('150301', 'Çã¼ºµ·', '1400450');
Insert into HAEUN.HR_MASTER_INFO   (EMPLOYEE_KEY, EMPLOYEE_NAME, ORGANIZATION_CODE) Values   ('151026', 'ÀÌÁ¾¿ø', '2300400');
Insert into HAEUN.HR_MASTER_INFO   (EMPLOYEE_KEY, EMPLOYEE_NAME, ORGANIZATION_CODE) Values   ('220221', '±è¸íÈÆ', '2300400');
Insert into HAEUN.HR_MASTER_INFO   (EMPLOYEE_KEY, EMPLOYEE_NAME, ORGANIZATION_CODE) Values   ('150302', '±è¿µÀº', '2300400'); 
Insert into HAEUN.HR_MASTER_INFO   (EMPLOYEE_KEY, EMPLOYEE_NAME, ORGANIZATION_CODE) Values   ('210712', 'ÇãÈñÀÚ', '1300200');
