CREATE TABLE HAEUN.AC_SLIP
(
  SLIP_CLS                  VARCHAR2(1 BYTE)          NOT NULL,
  SLIP_DATE                 VARCHAR2(8 BYTE)          NOT NULL,
  SLIP_NO                   VARCHAR2(3 BYTE)          NOT NULL,
  SLIP_SEQ                  VARCHAR2(3 BYTE)          NOT NULL,
  SLIP_SORT                 NUMBER(3)                 NOT NULL,
  ACCOUNT_DATE              VARCHAR2(8 BYTE),
  SLIP_KIND                 VARCHAR2(1 BYTE)          NOT NULL,
  GRP_CD                    VARCHAR2(4 BYTE)          NOT NULL,
  DTL_CD                    VARCHAR2(8 BYTE),
  CUST_CD                   VARCHAR2(5 BYTE),
  DEB_AMOUNT                NUMBER(15)                NOT NULL,
  CRE_AMOUNT                NUMBER(15)                NOT NULL,
  ORGANIZATION_CODE         VARCHAR2(7 BYTE),
  EMPLOYEE_KEY              VARCHAR2(10 BYTE)
)
TABLESPACE HAEUN_DAT;

CREATE UNIQUE INDEX HAEUN.AC_SLIP_PK ON HAEUN.AC_SLIP
(SLIP_CLS, SLIP_DATE, SLIP_NO, SLIP_SEQ)
LOGGING
TABLESPACE HAEUN_IDX;

ALTER TABLE HAEUN.AC_SLIP ADD (
  CONSTRAINT AC_SLIP_PK
  PRIMARY KEY
  (SLIP_CLS, SLIP_DATE, SLIP_NO, SLIP_SEQ)
  USING INDEX HAEUN.AC_SLIP_PK
  ENABLE VALIDATE);
  
-- 사원 정보 테이블
CREATE TABLE HAEUN.HR_MASTER_INFO
(
  EMPLOYEE_KEY              VARCHAR2(10 BYTE)         NOT NULL,
  EMPLOYEE_NAME             VARCHAR2(30 BYTE)         NOT NULL
)
TABLESPACE HAEUN_DAT;


CREATE UNIQUE INDEX HAEUN.HR_MASTER_INFO_PK ON HAEUN.HR_MASTER_INFO
(EMPLOYEE_KEY)
LOGGING
TABLESPACE HAEUN_IDX;

ALTER TABLE HAEUN.HR_MASTER_INFO ADD (
  CONSTRAINT HR_MASTER_INFO_PK
  PRIMARY KEY
  (EMPLOYEE_KEY)
  USING INDEX HAEUN.HR_MASTER_INFO_PK
  ENABLE VALIDATE);
  
-- 부서 정보 테이블
CREATE TABLE HAEUN.HR_CODE_ORGANIZATION
(
  ORGANIZATION_CODE         VARCHAR2(7 BYTE)          NOT NULL,
  ORGANIZATION_NAME         VARCHAR2(30 BYTE)         NOT NULL
)
TABLESPACE HAEUN_DAT;


CREATE UNIQUE INDEX HAEUN.HR_CODE_ORGANIZATION_PK ON HAEUN.HR_CODE_ORGANIZATION
(ORGANIZATION_CODE)
LOGGING
TABLESPACE HAEUN_IDX;

ALTER TABLE HAEUN.HR_CODE_ORGANIZATION ADD (
  CONSTRAINT HR_CODE_ORGANIZATION_PK
  PRIMARY KEY
  (ORGANIZATION_CODE)
  USING INDEX HAEUN.HR_CODE_ORGANIZATION_PK
  ENABLE VALIDATE);

