create table HR_MASTER_INFO (
EMPLOYEE_KEY        VARCHAR2(4)     NOT NULL,
EMPLOYEE_NAME       VARCHAR2(10)    NOT NULL,
ORGANIZATION_CODE   VARCHAR2(4)     NOT NULL, 
JOB_TITLE_CODE      VARCHAR2(4)     NOT NULL, 
ORGANITATION_NAME   VARCHAR2(30), 
JOB_TITLE_NAME      VARCHAR2(30), 
ENGLISH_GRADE       NUMBER(15,0), 
MATH_GRADE          NUMBER(15,0), 
KOREAN_GRADE        NUMBER(15,0), 
SUM_GRADE           NUMBER(15,0)) ;

CREATE TABLE HR_CODE_COMMON (
CODE_KIND       VARCHAR2(6)     NOT NULL,
CODE_CD         VARCHAR2(4)     NOT NULL, 
CODE_NAME       VARCHAR2(30)) ;

CREATE TABLE ENGLISH_TEST (
EMPLOYEE_KEY        VARCHAR2(4)     NOT NULL,
TEST_GRADE          NUMBER(15,0));

CREATE TABLE MATH_TEST (
EMPLOYEE_KEY        VARCHAR2(4)     NOT NULL,
TEST_GRADE          NUMBER(15,0));

CREATE TABLE KOREAN_TEST (
EMPLOYEE_KEY        VARCHAR2(4)     NOT NULL,
TEST_GRADE          NUMBER(15,0));


-- INSERT INTO >ø¢ºø∆ƒ¿œ∑Œ µ•¿Ã≈Õ ª¿‘«ﬂ¿Ω

COMMIT;

ALTER TABLE HR_MASTER_INFO ADD(
CONSTRAINT INFO_PK
PRIMARY KEY(EMPLOYEE_KEY)) ;

ALTER TABLE HR_CODE_COMMON ADD(
CONSTRAINT COMMON_PK
PRIMARY KEY(CODE_KIND, CODE_CD));



ALTER TABLE ENGLISH_TEST ADD(
CONSTRAINT ENG_PK
PRIMARY KEY(EMPLOYEE_KEY)) ;

ALTER TABLE MATH_TEST ADD(
CONSTRAINT MAT_PK
PRIMARY KEY(EMPLOYEE_KEY)) ;

ALTER TABLE KOREAN_TEST ADD(
CONSTRAINT KOR_PK
PRIMARY KEY(EMPLOYEE_KEY)) ;



ALTER TABLE HR_MASTER_INFO
MODIFY(ENGLISH_GRADE  DEFAULT 0);

ALTER TABLE HR_MASTER_INFO
MODIFY(MATH_GRADE  DEFAULT 0);

ALTER TABLE HR_MASTER_INFO
MODIFY(KOREAN_GRADE  DEFAULT 0);

ALTER TABLE HR_MASTER_INFO
MODIFY(SUM_GRADE  DEFAULT 0);